kind: Deployment
apiVersion: apps/v1
metadata:
  name: vue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
        - name: vue-app
          image: kpradeeprao/vue-app:v6
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: '128Mi'
              cpu: '100m'
      restartPolicy: Always
